spring.application.name=ec
server.port=8080
spring.devtools.restart.enabled=true
spring.jackson.date-format=yyyy-MM-dd
spring.jackson.time-zone=GMT+8
spring.datasource.url=jdbc:mysql://localhost:3306/demo?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=123456

#????
#spring.application.name=ec
#server.port=8080
#spring.devtools.restart.enabled=true
#spring.jackson.date-format=yyyy-MM-dd
#spring.jackson.time-zone=GMT+8
#spring.datasource.url=jdbc:mysql://localhost:3306/first?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
#spring.datasource.username=root
#spring.datasource.password=rpBhLNbhMHhyj8S6

# MyBatis-Plus
mybatis-plus.mapper-locations=classpath:mapper/*.xml
mybatis-plus.type-aliases-package=com.example.text.entity
mybatis-plus.configuration.map-underscore-to-camel-case=true
mybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl

#redis
spring.redis.host=localhost
spring.redis.port=6379

# ??
spring.mail.host=smtp.qq.com
spring.mail.port=465
spring.mail.username=2099704595@qq.com
spring.mail.password=milympibzclefffe
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.socketFactory.port=465
spring.mail.properties.mail.smtp.ssl.socketFactory.class=javax.net.ssl.SSLSocketFactory

#deepseek
deepseek.api-key=sk-3bcc1bdd3a5b40fdaf66e41f479ea95e
deepseek.url=https://api.deepseek.com/chat/completions
deepseek.model=deepseek-chat

